The AWS CloudFormation templates for this Quick Start includes configuration parameters that you can customize. Some of these settings, such as instance type or the Amazon-provided license included AMI for Windows Server, affects the cost of deployment. See the pricing pages for each AWS service you will be using for cost estimates.

The use of Microsoft software is subject to Microsoft's terms. You are responsible for complying with Microsoft licensing. This document is only a guide for your convenience and you are not entitled to rely on its descriptions and it does not constitute legal advice. If you have questions about your licensing or rights to Microsoft software, consult your legal team, Microsoft, or your Microsoft reseller. For more information, see https://www.microsoft.com/en-us/licensing/product-licensing/products.aspx[Microsoft Product Terms].

The Quick Start is configured to accept the following two licensing options.

==== Bring your own license (BYOL) AMI

Use your volume licensing software and bring the license. When using your own Window Server license, you must either import your own VM images or use host-based replication software to create the AMI. 

Several Amazon Machine Images (AMIs) that support a variety of operating system platforms and features are available to choose when launching your instances. To understand how the AMI you choose when launching your instance affects your AWS bill, you can research the associated operating system platform and billing information.

License Manager helps you with license reporting, governance, and managing true-ups and audits. However, Microsoft licensing requires you to bring your own media, which involves managing patching, updates, and golden AMI creation. 

To learn more about creating a BYOL AMI, see https://aws.amazon.com/blogs/modernizing-with-aws/how-to-create-windows-server-bring-your-own-license-amis-from-on-premises-with-vm-import-export/[How to create Windows Server Bring-Your-Own-License AMIs from on-premises with VM Import/Export].

The following lists platform details and usage operation values that can be displayed on the instances or AMI pages in the Amazon EC2 console, or in the response that is returned by the describe-images command. To learn more about billing codes and AMIs, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/billing-info-fields.html[AMI billing information fields]

* Windows License Included: RunInstances:0002
* Windows BYOL: RunInstances:0800

==== AMI for Windows Server with license costs included

Use the AMI for Windows Server with license costs included. When using AWS-provided Windows Server licensing, you don't need to import your own Windows images.

Run Windows Server instances on {partner-product-short-name} and use existing compliant Windows Server software licenses from AWS with a pay-as-you-go model. This helps in scenarios where you have eligible software licenses to use on {partner-product-short-name} but do not have accompanying Windows Server licenses to run the eligible software to the {partner-product-short-name} environment. 

You can use the Windows Server AMIs via the AWS Management Console, APIs, and the Command Line Interface (CLI). 
