// Replace the content in <>
// Identify your target audience and explain how/why they would use this Quick Start.
//Avoid borrowing text from third-party websites (copying text from AWS service documentation is fine). Also, avoid marketing-speak, focusing instead on the technical aspect.

This guide provides instructions for deploying an Amazon Elastic Compute Cloud (Amazon EC2) {partner-product-short-name} for Microsoft Quick Start reference architecture on the AWS Cloud. 

This Quick Start is for IT infrastructure architects, administrators, and DevOps professionals who are planning to implement a {partner-product-short-name} environment while bringing their own eligible Microsoft software licenses to AWS. 

The Quick Start automates the process of setting up the https://console.aws.amazon.com/license-manager/home?region=us-east-1#[AWS License Manager] license configuration and associating it with a https://console.aws.amazon.com/license-manager/home?region=us-east-1#/resourceGroups[host resource group]. Next, it creates an Auto Scaling group of EC2 {partner-product-short-name} instances, which are then assigned to the host resource group. The host resource group lets you manage the instances as a single entity based on your License Manager configuration settings. As you add new licenses to the License Manager configuration, the licenses are automatically applied to the new instances.  

=== Advantages

When deploying this Quick Start, you can:

* Benefit from the efficiencies of the AWS Cloud while using existing investments in on-premises
software
* Extend the lifecycle of prior software versions
* Import your existing Windows images to the AWS Cloud
* Easily track licenses using License Manager
* Enforce licensing rules, stay compliant, and control overages
* Centrally report usage and discover installed software

==== Eligible software 

You can use a variety of existing software licenses on AWS using {partner-product-short-name}, for example:

*  Microsoft Windows Server 2008*, 2008 R2*, 2012, 2016, or 2019
*  Microsoft SQL Server
*  Microsoft Remote Desktop Services
*  Microsoft Exchange Server 
*  Microsoft SharePoint Server 

[.small]#* Windows Server 2008 and 2008 R2 are no longer supported. If using these versions, you must bring your own image. For more information, see https://aws.amazon.com/emp-windows-server/[End-of-Support Migration Program for Windows Server].# 

