// Replace the content in <>
// Identify your target audience and explain how/why they would use this Quick Start.
//Avoid borrowing text from third-party websites (copying text from AWS service documentation is fine). Also, avoid marketing-speak, focusing instead on the technical aspect.

This guide provides instructions for deploying the {partner-product-short-name} Quick Start reference architecture on the AWS Cloud.

This Quick Start is for IT infrastructure architects, administrators, and DevOps professionals who are planning to implement EC2 Dedicated host environment to bring their own eligible software licenses to AWS.

== EC2 Dedicated Infrastructure ==

EC2 dedicated provides Dedicated hardware to support existing software licenses and improve compliance
Amazon EC2 Dedicated Hosts allow you to use your eligible software licenses from vendors such as Microsoft Windows Server or SQL Server on Amazon EC2, so that you get 
the flexibility and cost effectiveness of using your own licenses, but with the resiliency, simplicity and elasticity of AWS

An Amazon EC2 Dedicated Host is a physical server fully dedicated for your use, so you can help address corporate compliance requirements.

Amazon EC2 Dedicated Host is also integrated with AWS License Manager, a service which helps you manage your software licenses, 
including Microsoft Windows Server and Microsoft SQL Server licenses. In License Manager, you can specify your licensing terms for governing 
license usage, as well as your Dedicated Host management preferences for host allocation and host capacity utilization. Once setup, AWS takes care 
of these administrative tasks on your behalf, so that you can seamlessly launch virtual machines (instances) on Dedicated Hosts just like you would 
launch an EC2 instance with AWS provided licenses.
To learn more , please visit https://aws.amazon.com/ec2/dedicated-hosts/


=== License Manager ===

AWS License Manager makes it easier to manage your software licenses from vendors such as Microsoft, SAP, Oracle, and IBM, across AWS and on-premises environments. 
This gives you better control and visibility of your licenses, allowing you to limit licensing overages and reduce the risk of non-compliance and misreporting.

* Visibility of sockets and physical cores
* Affinity
* Instance placement controls
* Multiple instance size support
* Integrated license management

To learn more , please visit https://aws.amazon.com/license-manager/


=== Host Resource Group ===
A host resource group is a collection of Dedicated Hosts that you can manage as a single entity. As you launch instances, License Manager allocates the hosts and launches instances
 on them based on the settings that you configured. You can add existing Dedicated Hosts to a host resource group and take advantage of automated host management through License Manager.

You can use host resource groups to separate hosts by purpose, for example, development test hosts versus production, organizational unit, or license constraint. After you add a Dedicated 
Host to a host resource group, you cannot launch instances directly on the Dedicated Host, you must launch them using the host resource group.

The QuickStart will present you with parameters to specify your preference for host resource groups.

Host resource group will use them to do the automate following:

* Host allocation
* Instance placement
* Allowed Instance Family to create a collection of dedicated hosts as per your license limit.
* Host release
* Host recovery

To learn more about host resource group. Please visit 
https://docs.aws.amazon.com/license-manager/latest/userguide/host-resource-groups.html


=== BYOL AMI ===
There are many Amazon Machine Images (AMIs) to choose from when launching your instances, and they support a variety of operating system platforms and features. 
To understand how the AMI you choose when launching your instance affects the bottom line on your AWS bill, you can research the associated operating system platform and billing information

BYOL(Bring your own License) AMI are sourced from customer environment either using migration tool such as CloudEndure or VMImport/Export. 
BYOL AMI carry billing code RunInstances:0800 

To learn more about creating BYOL AMI , 

please visit https://aws.amazon.com/blogs/modernizing-with-aws/how-to-create-windows-server-bring-your-own-license-amis-from-on-premises-with-vm-import-export/


|===
|Platform details | Usage operation

// Space needed to maintain table headers
|Windows License Included |RunInstances:0002
|Windows BYOL |RunInstances:0800
|===
