// Replace the content in <>
// Identify your target audience and explain how/why they would use this Quick Start.
//Avoid borrowing text from third-party websites (copying text from AWS service documentation is fine). Also, avoid marketing-speak, focusing instead on the technical aspect.

This guide provides instructions for deploying an Amazon Elastic Compute Cloud (Amazon EC2) {partner-product-short-name} for Microsoft Quick Start reference architecture on the AWS Cloud. 

This Quick Start is for IT infrastructure architects, administrators, and DevOps professionals who are planning to implement a {partner-product-short-name} environment while bringing their own eligible Microsoft software licenses to AWS. 

The Quick Start automates the process of setting up the https://console.aws.amazon.com/license-manager/home?region=us-east-1#[AWS License Manager] license configuration and associating it with a https://console.aws.amazon.com/license-manager/home?region=us-east-1#/resourceGroups[host resource group]. Next, an Auto Scaling group of EC2 {partner-product-short-name} instances is created, and its hosts are assigned to the host resource group. As you add new licenses to the License Manager configuration, the licenses are automatically applied to the new instances.  

=== Advantages

When deploying this Quick Start, you can:

* Benefit from the efficiencies of the AWS Cloud while using existing investments in on-premises
software
* Extend the lifecycle of prior software versions
* Import your existing Windows images to the AWS Cloud
* Easily track licenses using License Manager
* Enforce licensing rules, stay compliant, and control overages
* Centrally report usage and discover installed software

==== Eligible software 

You can use a variety of existing software licenses on AWS using {partner-product-short-name}, for example:

*  Microsoft Windows Server 2008, 2008 R2, 2012, or 2016
*  Microsoft SQL Server
*  Microsoft Remote Desktop Services
*  Microsoft Exchange Server 
*  Microsoft SharePoint Server 

=== {partner-product-name} infrastructure

{partner-product-short-name} provide dedicated hardware to support existing software licenses. Using {partner-product-short-name}, you can take advantage of the flexibility and cost effectiveness of using your own licenses, but with the resiliency, simplicity, and elasticity of AWS.

A Dedicated Host is a physical server fully dedicated for your use, so you can address corporate compliance requirements.

==== AWS License Manager

{partner-product-short-name} also runs with AWS License Manager, a service that helps you manage your software licenses. In License Manager, you can specify your licensing terms for governing 
license usage, and you can configure your {partner-product-short-name} management preferences for host allocation and host capacity usage. After configuration is completed, AWS takes care of these administrative tasks on your behalf, so that you can seamlessly launch virtual machines (instances) on {partner-product-short-name}, similar to how you would launch an EC2 instance with an AWS-provided license. To learn more, see https://aws.amazon.com/ec2/dedicated-hosts/[Amazon EC2 Dedicated Hosts].

To learn more, see https://aws.amazon.com/license-manager/[AWS License Manager].

==== Host resource group

A host resource group is a collection of {partner-product-short-name} that you can manage as a single entity. As you launch instances, License Manager allocates the hosts and launches instances on them based on your configuration settings. You can add existing {partner-product-short-name} to a host resource group and take advantage of automated host management through License Manager.

You can use host resource groups to separate hosts by purpose (for example, development test hosts versus production, organizational unit, or license constraints). After you add a Dedicated Host to a host resource group, you cannot launch instances directly on the Dedicated Host. Instead, you must launch them using the host resource group.

The Quick Start provides parameters for the host resource group. These parameters automate the following:

* Host allocation
* Instance placement
* Allowed instance family to create a collection of {partner-product-short-name} per your license limit
* Host release
* Host recovery

To learn more about host resource groups, see 
https://docs.aws.amazon.com/license-manager/latest/userguide/host-resource-groups.html[Host resource groups in AWS License Manager].




